GET http://localhost:8080/students HTTP/1.1

# GET All Students 
# GET https://wlatracker2.onrender.com/students

# # GET Student by ID 
# GET https://wlatracker2.onrender.com/students/63c34c6972c9bcf6024e1109

# CREATE Student Local
# POST http://localhost:8080/students HTTP/1.1 Content-Type: application/json

# {
#     "firstName":"Jose",
#     "lastName":"Reyes",
#     "email":"jose.reyes@gmail.com",
#     "birthday":"04/19/1981",
#     "studentLevel":"Sifu"
# }

# CREATE Student
# POST https://wlatracker2.onrender.com/students HTTP/1.1 Content-Type: application/json

# {
#     "firstName":"Jose",
#     "lastName":"Reyes",
#     "email":"jose.reyes@gmail.com",
#     "birthday":"04/19/1981",
#     "studentLevel":"Sifu"
# }

# # # # PUT Student Local
# PUT http://localhost:8080/students/63e5b40e36154df5b9fc094e HTTP/1.1 
# Content-Type: application/json

# {
#     "firstName":"Jose",
#     "lastName":"Reyes",
#     "email":"jose.reyes@gmail.com",
#     "birthday":"04/19/1981",
#     "studentLevel":"Sifu"
# }


# # # # PUT Student
# PUT https://wlatracker2.onrender.com/students/63c34c6972c9bcf6024e1109 HTTP/1.1 
# Content-Type: application/json

# {
#     "firstName":"Andrew",
#     "lastName":"Lin",
#     "email":"drewboy64@gmail.com",
#     "birthday":"06/15/1986",
#     "studentLevel":"Technician"
# }

# # DELETE Student
# DELETE https://wlatracker2.onrender.com/students/63cca7fcaaa23af10c244684 HTTP/1.1